image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - build
  - test
  - push

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-backend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME-untested .
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME-untested

test-backend:
  stage: test
  script:
    - echo TODO

build-telnet-frontend:
  stage: build
  script:
  - cd frontend/telnet
  - docker build -t $CI_REGISTRY_IMAGE/frontend/telnet:$CI_COMMIT_REF_NAME-untested .
  - docker push $CI_REGISTRY_IMAGE/frontend/telnet:$CI_COMMIT_REF_NAME-untested

push-verified:
  stage: push
  script:
    - docker pull $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME-untested
    - docker pull $CI_REGISTRY_IMAGE/frontend/telnet:$CI_COMMIT_REF_NAME-untested

    - docker tag $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME-backend-untested $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE/frontend/telnet:$CI_COMMIT_REF_NAME-untested $CI_REGISTRY_IMAGE/frontend/telnet:$CI_COMMIT_REF_NAME

    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE/frontend/telnet:$CI_COMMIT_REF_NAME
